### PR TITLE
guard remainder stubs

### PR DESCRIPTION
**Pull request by soypat**
PTAL

### CODE REVIEW

**Comment by chewxy** [comment]
Is there a way to guard these using build tags instead of `if` statements?

**Comment by soypat** [comment]
@chewxy That is a good question. This is how the the standard library is doing things now https://github.com/golang/go/tree/master/src/math.

I'm not sure why they use the if statement, but it does provide an advantage for my use case with `tinygo`: it allows me to use functions that are stubs, otherwise the project just would not build.

According to Chris Cunningham on slack:
> looks like so it can still be supported in a situation where there is not a per architecture way provided

**Comment by soypat** [comment]
Here's the complete summary: https://github.com/golang/go/commit/1d20a362d0ca4898d77865e314ef6f73582daef0

**Comment by soypat** [comment]
@chewxy Let me know if I can clear anything up regarding the changes :)

**Pull request merged**
